### ISSUE TITLE
Comparison with cloudbase-init

### ISSUE THREAD

**Issue by kvaps** [LINBIT/cloud-init-for-windows#1]
Hi, such an interesting project!
What is the difference with [cloudbase-init](https://github.com/cloudbase/cloudbase-init)?

**Comment by johannesthoma** [comment]
Hi @kvaps thank you :) 

I have to admit that I wasn't aware of cloudbase-init. Furthermore it
was intended to be used only in our internal CI pipeline (which uses
[virter](https://github.com/LINBIT/virter) which in turn uses cloud-init)
originally. It is still (and probably will remain) incomplete and does
only the things we need (which is hostname, ssh and cygsshd starting)
and also only supports cloud-init. If you want to use it in your projects
that would be great, the shell script can also easily be extended.

**Comment by johannesthoma** [comment]
There is also the doc/windows.md file in virter which explains how to
setup a Windows VM, which referenced this cloud-init-for-windows
project which was the main reason for publishing it.

**Comment by johannesthoma** [comment]
Hi I think I will close this now, feel free to reopen if you have questions.
